# Generated by Django 5.1.4 on 2025-01-23 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_reply_author_alter_topic_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='topics', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='base.reply'),
        ),
    ]
